//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34209
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{

	/*
	 * Passive -> Alert -> Investegating -> Looking -> Passive...
	 *
	 * Desc.
	 * Passive : He does nothing.
	 * Looking : He looks for the player.
	 * Alert : He heard a noise and is preparing to investegate.
	 * Moveing : He walks to the nosie.
	 * Tracing : He follows the noise-giver.
	 * 
	 * Prio.
	 * Passive < Looking < Alert < Moveing < Tracing
	 * 
	 */

	public enum State
	{
		Passive = 0,
		Looking = 1,
		Alert = 2,
		Moveing = 3,
		Tracing = 4
	}
}

