//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34209
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;
namespace AssemblyCSharp
{
	public class Vision : MonoBehaviour
	{

		public float fov = 90;
		public float distance = 10;


		private Transform eyes;
		private Transform player;
		private float angle;

		void Awake ()
		{
			player = GameObject.FindGameObjectWithTag ("Player").transform;
			eyes = gameObject.GetComponent<Transform> ();
		}

		public bool CanSeePlayer ()
		{
			RaycastHit hit;
			if (Physics.Raycast (eyes.position, player.position - eyes.position, out hit, distance) && 
				Mathf.Abs (Vector3.Angle (eyes.transform.position - player.transform.position, 
			               -gameObject.transform.forward)) <= fov) {
				return hit.collider.gameObject.CompareTag ("Player");
			}
			return false;
		}
	}
}

