//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.34209
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	public class SoundLength
	{
		public static float GetPathLength (NavMeshPath path, Vector3 you)
		{
			float length = 0;
			for (int i = -1; i < path.corners.Length-1; i++) {
				length += Vector3.Distance (((i == -1) ? you : path.corners [i]), path.corners [i + 1]);
			}
			length = (length == 0) ? Mathf.Infinity : length;
			return length;
		}
	}
}

